/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables;


import com.darkcom.backend.generate.Test;
import com.darkcom.backend.generate.tables.records.GroupQuotaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupQuota extends TableImpl<GroupQuotaRecord> {

    private static final long serialVersionUID = -1814918797;

    /**
     * The reference instance of <code>test.t_group_quota</code>
     */
    public static final GroupQuota T_GROUP_QUOTA = new GroupQuota();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupQuotaRecord> getRecordType() {
        return GroupQuotaRecord.class;
    }

    /**
     * The column <code>test.t_group_quota.group_id</code>.
     */
    public final TableField<GroupQuotaRecord, String> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>test.t_group_quota.quota_balance</code>.
     */
    public final TableField<GroupQuotaRecord, Integer> QUOTA_BALANCE = createField("quota_balance", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_group_quota.quota_limit</code>.
     */
    public final TableField<GroupQuotaRecord, Integer> QUOTA_LIMIT = createField("quota_limit", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_group_quota.created_time</code>.
     */
    public final TableField<GroupQuotaRecord, LocalDateTime> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>test.t_group_quota</code> table reference
     */
    public GroupQuota() {
        this(DSL.name("t_group_quota"), null);
    }

    /**
     * Create an aliased <code>test.t_group_quota</code> table reference
     */
    public GroupQuota(String alias) {
        this(DSL.name(alias), T_GROUP_QUOTA);
    }

    /**
     * Create an aliased <code>test.t_group_quota</code> table reference
     */
    public GroupQuota(Name alias) {
        this(alias, T_GROUP_QUOTA);
    }

    private GroupQuota(Name alias, Table<GroupQuotaRecord> aliased) {
        this(alias, aliased, null);
    }

    private GroupQuota(Name alias, Table<GroupQuotaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GroupQuotaRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.darkcom.backend.generate.tables.GroupQuota.T_GROUP_QUOTA, "KEY_t_group_quota_PRIMARY", com.darkcom.backend.generate.tables.GroupQuota.T_GROUP_QUOTA.GROUP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GroupQuotaRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupQuotaRecord>>asList(
              Internal.createUniqueKey(com.darkcom.backend.generate.tables.GroupQuota.T_GROUP_QUOTA, "KEY_t_group_quota_PRIMARY", com.darkcom.backend.generate.tables.GroupQuota.T_GROUP_QUOTA.GROUP_ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuota as(String alias) {
        return new GroupQuota(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuota as(Name alias) {
        return new GroupQuota(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupQuota rename(String name) {
        return new GroupQuota(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GroupQuota rename(Name name) {
        return new GroupQuota(name, null);
    }
}
