/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables;


import com.darkcom.backend.generate.Test;
import com.darkcom.backend.generate.tables.records.QuotaDetailRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuotaDetail extends TableImpl<QuotaDetailRecord> {

    private static final long serialVersionUID = 1507827389;

    /**
     * The reference instance of <code>test.t_quota_detail</code>
     */
    public static final QuotaDetail T_QUOTA_DETAIL = new QuotaDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuotaDetailRecord> getRecordType() {
        return QuotaDetailRecord.class;
    }

    /**
     * The column <code>test.t_quota_detail.detail_id</code>.
     */
    public final TableField<QuotaDetailRecord, Integer> DETAIL_ID = createField("detail_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test.t_quota_detail.group_id</code>.
     */
    public final TableField<QuotaDetailRecord, String> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>test.t_quota_detail.quota_balance</code>.
     */
    public final TableField<QuotaDetailRecord, Integer> QUOTA_BALANCE = createField("quota_balance", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_quota_detail.quota_limit</code>.
     */
    public final TableField<QuotaDetailRecord, Integer> QUOTA_LIMIT = createField("quota_limit", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_quota_detail.personal_quota</code>.
     */
    public final TableField<QuotaDetailRecord, Integer> PERSONAL_QUOTA = createField("personal_quota", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_quota_detail.start_time</code>.
     */
    public final TableField<QuotaDetailRecord, LocalDateTime> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>test.t_quota_detail.end_time</code>.
     */
    public final TableField<QuotaDetailRecord, LocalDateTime> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>test.t_quota_detail.status</code>.
     */
    public final TableField<QuotaDetailRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_quota_detail.posi_id</code>.
     */
    public final TableField<QuotaDetailRecord, Integer> POSI_ID = createField("posi_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>test.t_quota_detail.posi_name</code>.
     */
    public final TableField<QuotaDetailRecord, String> POSI_NAME = createField("posi_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.t_quota_detail.created_time</code>.
     */
    public final TableField<QuotaDetailRecord, LocalDateTime> CREATED_TIME = createField("created_time", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>test.t_quota_detail</code> table reference
     */
    public QuotaDetail() {
        this(DSL.name("t_quota_detail"), null);
    }

    /**
     * Create an aliased <code>test.t_quota_detail</code> table reference
     */
    public QuotaDetail(String alias) {
        this(DSL.name(alias), T_QUOTA_DETAIL);
    }

    /**
     * Create an aliased <code>test.t_quota_detail</code> table reference
     */
    public QuotaDetail(Name alias) {
        this(alias, T_QUOTA_DETAIL);
    }

    private QuotaDetail(Name alias, Table<QuotaDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuotaDetail(Name alias, Table<QuotaDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<QuotaDetailRecord> getPrimaryKey() {
        return Internal.createUniqueKey(com.darkcom.backend.generate.tables.QuotaDetail.T_QUOTA_DETAIL, "KEY_t_quota_detail_PRIMARY", com.darkcom.backend.generate.tables.QuotaDetail.T_QUOTA_DETAIL.DETAIL_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<QuotaDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<QuotaDetailRecord>>asList(
              Internal.createUniqueKey(com.darkcom.backend.generate.tables.QuotaDetail.T_QUOTA_DETAIL, "KEY_t_quota_detail_PRIMARY", com.darkcom.backend.generate.tables.QuotaDetail.T_QUOTA_DETAIL.DETAIL_ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetail as(String alias) {
        return new QuotaDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetail as(Name alias) {
        return new QuotaDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuotaDetail rename(String name) {
        return new QuotaDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuotaDetail rename(Name name) {
        return new QuotaDetail(name, null);
    }
}
