server:
  port: 80
spring:
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,resources/**,static/**,templates/**
  datasource:
    name: demo
    url: jdbc:mysql://123.57.241.67:3306/test
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#wechat config
wx:
  miniapp:
    configs:
    - appid: wxa063d9ac87b09c0c
      secret: f9914d6ef6a354dd905530d06e8b48d4
      token: miniApp
      aesKey: AgRiat0snfTaz1V5CDrpViAReeoBiWyx2PPY6Ms1531
      msgDataFormat: JSON

logging:
  path: d:/log/test
  config: classpath:logback-spring.xml
