/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupQuota implements Serializable {

    private static final long serialVersionUID = 156968486;

    private String        groupId;
    private Integer       quotaBalance;
    private Integer       quotaLimit;
    private LocalDateTime createdTime;

    public GroupQuota() {}

    public GroupQuota(GroupQuota value) {
        this.groupId = value.groupId;
        this.quotaBalance = value.quotaBalance;
        this.quotaLimit = value.quotaLimit;
        this.createdTime = value.createdTime;
    }

    public GroupQuota(
        String        groupId,
        Integer       quotaBalance,
        Integer       quotaLimit,
        LocalDateTime createdTime
    ) {
        this.groupId = groupId;
        this.quotaBalance = quotaBalance;
        this.quotaLimit = quotaLimit;
        this.createdTime = createdTime;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Integer getQuotaBalance() {
        return this.quotaBalance;
    }

    public void setQuotaBalance(Integer quotaBalance) {
        this.quotaBalance = quotaBalance;
    }

    public Integer getQuotaLimit() {
        return this.quotaLimit;
    }

    public void setQuotaLimit(Integer quotaLimit) {
        this.quotaLimit = quotaLimit;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GroupQuota (");

        sb.append(groupId);
        sb.append(", ").append(quotaBalance);
        sb.append(", ").append(quotaLimit);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
