/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuotaDetail implements Serializable {

    private static final long serialVersionUID = -80063297;

    private Integer       detailId;
    private String        groupId;
    private Integer       quotaBalance;
    private Integer       quotaLimit;
    private Integer       personalQuota;
    private LocalDateTime startTime;
    private LocalDateTime endTime;
    private Integer       status;
    private Integer       posiId;
    private String        posiName;
    private LocalDateTime createdTime;

    public QuotaDetail() {}

    public QuotaDetail(QuotaDetail value) {
        this.detailId = value.detailId;
        this.groupId = value.groupId;
        this.quotaBalance = value.quotaBalance;
        this.quotaLimit = value.quotaLimit;
        this.personalQuota = value.personalQuota;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
        this.status = value.status;
        this.posiId = value.posiId;
        this.posiName = value.posiName;
        this.createdTime = value.createdTime;
    }

    public QuotaDetail(
        Integer       detailId,
        String        groupId,
        Integer       quotaBalance,
        Integer       quotaLimit,
        Integer       personalQuota,
        LocalDateTime startTime,
        LocalDateTime endTime,
        Integer       status,
        Integer       posiId,
        String        posiName,
        LocalDateTime createdTime
    ) {
        this.detailId = detailId;
        this.groupId = groupId;
        this.quotaBalance = quotaBalance;
        this.quotaLimit = quotaLimit;
        this.personalQuota = personalQuota;
        this.startTime = startTime;
        this.endTime = endTime;
        this.status = status;
        this.posiId = posiId;
        this.posiName = posiName;
        this.createdTime = createdTime;
    }

    public Integer getDetailId() {
        return this.detailId;
    }

    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Integer getQuotaBalance() {
        return this.quotaBalance;
    }

    public void setQuotaBalance(Integer quotaBalance) {
        this.quotaBalance = quotaBalance;
    }

    public Integer getQuotaLimit() {
        return this.quotaLimit;
    }

    public void setQuotaLimit(Integer quotaLimit) {
        this.quotaLimit = quotaLimit;
    }

    public Integer getPersonalQuota() {
        return this.personalQuota;
    }

    public void setPersonalQuota(Integer personalQuota) {
        this.personalQuota = personalQuota;
    }

    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getPosiId() {
        return this.posiId;
    }

    public void setPosiId(Integer posiId) {
        this.posiId = posiId;
    }

    public String getPosiName() {
        return this.posiName;
    }

    public void setPosiName(String posiName) {
        this.posiName = posiName;
    }

    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("QuotaDetail (");

        sb.append(detailId);
        sb.append(", ").append(groupId);
        sb.append(", ").append(quotaBalance);
        sb.append(", ").append(quotaLimit);
        sb.append(", ").append(personalQuota);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);
        sb.append(", ").append(status);
        sb.append(", ").append(posiId);
        sb.append(", ").append(posiName);
        sb.append(", ").append(createdTime);

        sb.append(")");
        return sb.toString();
    }
}
