/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relationship implements Serializable {

    private static final long serialVersionUID = -1982252456;

    private Integer id;
    private String  groupId;
    private Integer detailId;
    private String  type;
    private Integer posiId;

    public Relationship() {}

    public Relationship(Relationship value) {
        this.id = value.id;
        this.groupId = value.groupId;
        this.detailId = value.detailId;
        this.type = value.type;
        this.posiId = value.posiId;
    }

    public Relationship(
        Integer id,
        String  groupId,
        Integer detailId,
        String  type,
        Integer posiId
    ) {
        this.id = id;
        this.groupId = groupId;
        this.detailId = detailId;
        this.type = type;
        this.posiId = posiId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGroupId() {
        return this.groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public Integer getDetailId() {
        return this.detailId;
    }

    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getPosiId() {
        return this.posiId;
    }

    public void setPosiId(Integer posiId) {
        this.posiId = posiId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Relationship (");

        sb.append(id);
        sb.append(", ").append(groupId);
        sb.append(", ").append(detailId);
        sb.append(", ").append(type);
        sb.append(", ").append(posiId);

        sb.append(")");
        return sb.toString();
    }
}
