/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 小程序用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements Serializable {

    private static final long serialVersionUID = 452618102;

    private Long          id;
    private String        unionId;
    private String        openId;
    private String        phone;
    private String        nickName;
    private String        gender;
    private String        language;
    private String        city;
    private String        province;
    private String        country;
    private String        avatarUrl;
    private String        sessionKey;
    private String        createdBy;
    private LocalDateTime createDate;
    private String        updatedBy;
    private LocalDateTime updateDate;

    public UserInfo() {}

    public UserInfo(UserInfo value) {
        this.id = value.id;
        this.unionId = value.unionId;
        this.openId = value.openId;
        this.phone = value.phone;
        this.nickName = value.nickName;
        this.gender = value.gender;
        this.language = value.language;
        this.city = value.city;
        this.province = value.province;
        this.country = value.country;
        this.avatarUrl = value.avatarUrl;
        this.sessionKey = value.sessionKey;
        this.createdBy = value.createdBy;
        this.createDate = value.createDate;
        this.updatedBy = value.updatedBy;
        this.updateDate = value.updateDate;
    }

    public UserInfo(
        Long          id,
        String        unionId,
        String        openId,
        String        phone,
        String        nickName,
        String        gender,
        String        language,
        String        city,
        String        province,
        String        country,
        String        avatarUrl,
        String        sessionKey,
        String        createdBy,
        LocalDateTime createDate,
        String        updatedBy,
        LocalDateTime updateDate
    ) {
        this.id = id;
        this.unionId = unionId;
        this.openId = openId;
        this.phone = phone;
        this.nickName = nickName;
        this.gender = gender;
        this.language = language;
        this.city = city;
        this.province = province;
        this.country = country;
        this.avatarUrl = avatarUrl;
        this.sessionKey = sessionKey;
        this.createdBy = createdBy;
        this.createDate = createDate;
        this.updatedBy = updatedBy;
        this.updateDate = updateDate;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUnionId() {
        return this.unionId;
    }

    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getNickName() {
        return this.nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getSessionKey() {
        return this.sessionKey;
    }

    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public LocalDateTime getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserInfo (");

        sb.append(id);
        sb.append(", ").append(unionId);
        sb.append(", ").append(openId);
        sb.append(", ").append(phone);
        sb.append(", ").append(nickName);
        sb.append(", ").append(gender);
        sb.append(", ").append(language);
        sb.append(", ").append(city);
        sb.append(", ").append(province);
        sb.append(", ").append(country);
        sb.append(", ").append(avatarUrl);
        sb.append(", ").append(sessionKey);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createDate);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updateDate);

        sb.append(")");
        return sb.toString();
    }
}
