/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.records;


import com.darkcom.backend.generate.tables.GroupQuota;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupQuotaRecord extends UpdatableRecordImpl<GroupQuotaRecord> implements Record4<String, Integer, Integer, LocalDateTime> {

    private static final long serialVersionUID = -2093439096;

    /**
     * Setter for <code>test.t_group_quota.group_id</code>.
     */
    public void setGroupId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.t_group_quota.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test.t_group_quota.quota_balance</code>.
     */
    public void setQuotaBalance(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.t_group_quota.quota_balance</code>.
     */
    public Integer getQuotaBalance() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>test.t_group_quota.quota_limit</code>.
     */
    public void setQuotaLimit(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.t_group_quota.quota_limit</code>.
     */
    public Integer getQuotaLimit() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.t_group_quota.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.t_group_quota.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, Integer, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Integer, Integer, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GroupQuota.T_GROUP_QUOTA.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return GroupQuota.T_GROUP_QUOTA.QUOTA_BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GroupQuota.T_GROUP_QUOTA.QUOTA_LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return GroupQuota.T_GROUP_QUOTA.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getQuotaBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQuotaLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getQuotaBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuotaLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuotaRecord value1(String value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuotaRecord value2(Integer value) {
        setQuotaBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuotaRecord value3(Integer value) {
        setQuotaLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuotaRecord value4(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupQuotaRecord values(String value1, Integer value2, Integer value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupQuotaRecord
     */
    public GroupQuotaRecord() {
        super(GroupQuota.T_GROUP_QUOTA);
    }

    /**
     * Create a detached, initialised GroupQuotaRecord
     */
    public GroupQuotaRecord(String groupId, Integer quotaBalance, Integer quotaLimit, LocalDateTime createdTime) {
        super(GroupQuota.T_GROUP_QUOTA);

        set(0, groupId);
        set(1, quotaBalance);
        set(2, quotaLimit);
        set(3, createdTime);
    }
}
