/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.records;


import com.darkcom.backend.generate.tables.QuotaDetail;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuotaDetailRecord extends UpdatableRecordImpl<QuotaDetailRecord> implements Record11<Integer, String, Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, String, LocalDateTime> {

    private static final long serialVersionUID = -498123646;

    /**
     * Setter for <code>test.t_quota_detail.detail_id</code>.
     */
    public void setDetailId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.detail_id</code>.
     */
    public Integer getDetailId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.t_quota_detail.group_id</code>.
     */
    public void setGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.t_quota_detail.quota_balance</code>.
     */
    public void setQuotaBalance(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.quota_balance</code>.
     */
    public Integer getQuotaBalance() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.t_quota_detail.quota_limit</code>.
     */
    public void setQuotaLimit(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.quota_limit</code>.
     */
    public Integer getQuotaLimit() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>test.t_quota_detail.personal_quota</code>.
     */
    public void setPersonalQuota(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.personal_quota</code>.
     */
    public Integer getPersonalQuota() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>test.t_quota_detail.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>test.t_quota_detail.end_time</code>.
     */
    public void setEndTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.end_time</code>.
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>test.t_quota_detail.status</code>.
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>test.t_quota_detail.posi_id</code>.
     */
    public void setPosiId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.posi_id</code>.
     */
    public Integer getPosiId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>test.t_quota_detail.posi_name</code>.
     */
    public void setPosiName(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.posi_name</code>.
     */
    public String getPosiName() {
        return (String) get(9);
    }

    /**
     * Setter for <code>test.t_quota_detail.created_time</code>.
     */
    public void setCreatedTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>test.t_quota_detail.created_time</code>.
     */
    public LocalDateTime getCreatedTime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, String, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, String, Integer, Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, String, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return QuotaDetail.T_QUOTA_DETAIL.DETAIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return QuotaDetail.T_QUOTA_DETAIL.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return QuotaDetail.T_QUOTA_DETAIL.QUOTA_BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return QuotaDetail.T_QUOTA_DETAIL.QUOTA_LIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return QuotaDetail.T_QUOTA_DETAIL.PERSONAL_QUOTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return QuotaDetail.T_QUOTA_DETAIL.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return QuotaDetail.T_QUOTA_DETAIL.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return QuotaDetail.T_QUOTA_DETAIL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return QuotaDetail.T_QUOTA_DETAIL.POSI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return QuotaDetail.T_QUOTA_DETAIL.POSI_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field11() {
        return QuotaDetail.T_QUOTA_DETAIL.CREATED_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getQuotaBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuotaLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPersonalQuota();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPosiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getPosiName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component11() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuotaBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuotaLimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPersonalQuota();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPosiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getPosiName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value11() {
        return getCreatedTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value1(Integer value) {
        setDetailId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value2(String value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value3(Integer value) {
        setQuotaBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value4(Integer value) {
        setQuotaLimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value5(Integer value) {
        setPersonalQuota(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value6(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value7(LocalDateTime value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value9(Integer value) {
        setPosiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value10(String value) {
        setPosiName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord value11(LocalDateTime value) {
        setCreatedTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuotaDetailRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, LocalDateTime value6, LocalDateTime value7, Integer value8, Integer value9, String value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuotaDetailRecord
     */
    public QuotaDetailRecord() {
        super(QuotaDetail.T_QUOTA_DETAIL);
    }

    /**
     * Create a detached, initialised QuotaDetailRecord
     */
    public QuotaDetailRecord(Integer detailId, String groupId, Integer quotaBalance, Integer quotaLimit, Integer personalQuota, LocalDateTime startTime, LocalDateTime endTime, Integer status, Integer posiId, String posiName, LocalDateTime createdTime) {
        super(QuotaDetail.T_QUOTA_DETAIL);

        set(0, detailId);
        set(1, groupId);
        set(2, quotaBalance);
        set(3, quotaLimit);
        set(4, personalQuota);
        set(5, startTime);
        set(6, endTime);
        set(7, status);
        set(8, posiId);
        set(9, posiName);
        set(10, createdTime);
    }
}
