/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.records;


import com.darkcom.backend.generate.tables.Relationship;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelationshipRecord extends TableRecordImpl<RelationshipRecord> implements Record5<Integer, String, Integer, String, Integer> {

    private static final long serialVersionUID = 1270414668;

    /**
     * Setter for <code>test.t_relationship.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.t_relationship.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.t_relationship.group_id</code>.
     */
    public void setGroupId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.t_relationship.group_id</code>.
     */
    public String getGroupId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.t_relationship.detail_id</code>.
     */
    public void setDetailId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.t_relationship.detail_id</code>.
     */
    public Integer getDetailId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>test.t_relationship.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.t_relationship.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.t_relationship.posi_id</code>.
     */
    public void setPosiId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.t_relationship.posi_id</code>.
     */
    public Integer getPosiId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Relationship.T_RELATIONSHIP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Relationship.T_RELATIONSHIP.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Relationship.T_RELATIONSHIP.DETAIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Relationship.T_RELATIONSHIP.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Relationship.T_RELATIONSHIP.POSI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPosiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPosiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value2(String value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value3(Integer value) {
        setDetailId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord value5(Integer value) {
        setPosiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RelationshipRecord values(Integer value1, String value2, Integer value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelationshipRecord
     */
    public RelationshipRecord() {
        super(Relationship.T_RELATIONSHIP);
    }

    /**
     * Create a detached, initialised RelationshipRecord
     */
    public RelationshipRecord(Integer id, String groupId, Integer detailId, String type, Integer posiId) {
        super(Relationship.T_RELATIONSHIP);

        set(0, id);
        set(1, groupId);
        set(2, detailId);
        set(3, type);
        set(4, posiId);
    }
}
