/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.records;


import com.darkcom.backend.generate.tables.UserInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 小程序用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoRecord extends UpdatableRecordImpl<UserInfoRecord> implements Record16<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = -1029896728;

    /**
     * Setter for <code>miniapp.t_user_info.id</code>. 自增主键
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.id</code>. 自增主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>miniapp.t_user_info.union_id</code>. 微信联合ID，唯一
     */
    public void setUnionId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.union_id</code>. 微信联合ID，唯一
     */
    public String getUnionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>miniapp.t_user_info.open_id</code>. 微信开放ID，当前小程序下唯一
     */
    public void setOpenId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.open_id</code>. 微信开放ID，当前小程序下唯一
     */
    public String getOpenId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>miniapp.t_user_info.phone</code>. 手机号
     */
    public void setPhone(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.phone</code>. 手机号
     */
    public String getPhone() {
        return (String) get(3);
    }

    /**
     * Setter for <code>miniapp.t_user_info.nick_name</code>. 昵称
     */
    public void setNickName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.nick_name</code>. 昵称
     */
    public String getNickName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>miniapp.t_user_info.gender</code>. 性别
     */
    public void setGender(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.gender</code>. 性别
     */
    public String getGender() {
        return (String) get(5);
    }

    /**
     * Setter for <code>miniapp.t_user_info.language</code>. 语言
     */
    public void setLanguage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.language</code>. 语言
     */
    public String getLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>miniapp.t_user_info.city</code>. 城市
     */
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.city</code>. 城市
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>miniapp.t_user_info.province</code>. 省份
     */
    public void setProvince(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(8);
    }

    /**
     * Setter for <code>miniapp.t_user_info.country</code>. 国家
     */
    public void setCountry(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.country</code>. 国家
     */
    public String getCountry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>miniapp.t_user_info.avatar_url</code>. 头像url
     */
    public void setAvatarUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.avatar_url</code>. 头像url
     */
    public String getAvatarUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>miniapp.t_user_info.session_key</code>. 微信会话key
     */
    public void setSessionKey(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.session_key</code>. 微信会话key
     */
    public String getSessionKey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>miniapp.t_user_info.created_by</code>. 创建者
     */
    public void setCreatedBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.created_by</code>. 创建者
     */
    public String getCreatedBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>miniapp.t_user_info.create_date</code>. 创建时间
     */
    public void setCreateDate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.create_date</code>. 创建时间
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>miniapp.t_user_info.updated_by</code>. 更新人
     */
    public void setUpdatedBy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.updated_by</code>. 更新人
     */
    public String getUpdatedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>miniapp.t_user_info.update_date</code>. 更新时间
     */
    public void setUpdateDate(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>miniapp.t_user_info.update_date</code>. 更新时间
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Long, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserInfo.T_USER_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserInfo.T_USER_INFO.UNION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserInfo.T_USER_INFO.OPEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserInfo.T_USER_INFO.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserInfo.T_USER_INFO.NICK_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return UserInfo.T_USER_INFO.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserInfo.T_USER_INFO.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserInfo.T_USER_INFO.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserInfo.T_USER_INFO.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return UserInfo.T_USER_INFO.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return UserInfo.T_USER_INFO.AVATAR_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return UserInfo.T_USER_INFO.SESSION_KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return UserInfo.T_USER_INFO.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return UserInfo.T_USER_INFO.CREATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return UserInfo.T_USER_INFO.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field16() {
        return UserInfo.T_USER_INFO.UPDATE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUnionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getAvatarUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getSessionKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component14() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component16() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUnionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNickName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getAvatarUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getSessionKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value16() {
        return getUpdateDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value2(String value) {
        setUnionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value3(String value) {
        setOpenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value4(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value5(String value) {
        setNickName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value6(String value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value7(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value8(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value9(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value10(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value11(String value) {
        setAvatarUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value12(String value) {
        setSessionKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value13(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value14(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value15(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord value16(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserInfoRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, LocalDateTime value14, String value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserInfoRecord
     */
    public UserInfoRecord() {
        super(UserInfo.T_USER_INFO);
    }

    /**
     * Create a detached, initialised UserInfoRecord
     */
    public UserInfoRecord(Long id, String unionId, String openId, String phone, String nickName, String gender, String language, String city, String province, String country, String avatarUrl, String sessionKey, String createdBy, LocalDateTime createDate, String updatedBy, LocalDateTime updateDate) {
        super(UserInfo.T_USER_INFO);

        set(0, id);
        set(1, unionId);
        set(2, openId);
        set(3, phone);
        set(4, nickName);
        set(5, gender);
        set(6, language);
        set(7, city);
        set(8, province);
        set(9, country);
        set(10, avatarUrl);
        set(11, sessionKey);
        set(12, createdBy);
        set(13, createDate);
        set(14, updatedBy);
        set(15, updateDate);
    }
}
