/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate;


import com.darkcom.backend.generate.tables.UserInfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Miniapp extends SchemaImpl {

    private static final long serialVersionUID = 1850973135;

    /**
     * The reference instance of <code>miniapp</code>
     */
    public static final Miniapp MINIAPP = new Miniapp();

    /**
     * 小程序用户信息
     */
    public final UserInfo T_USER_INFO = com.darkcom.backend.generate.tables.UserInfo.T_USER_INFO;

    /**
     * No further instances allowed
     */
    private Miniapp() {
        super("miniapp", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            UserInfo.T_USER_INFO);
    }
}
