/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate;


import com.darkcom.backend.generate.tables.UserInfo;


/**
 * Convenience access to all tables in miniapp
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 小程序用户信息
     */
    public static final UserInfo T_USER_INFO = com.darkcom.backend.generate.tables.UserInfo.T_USER_INFO;
}
