/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.daos;


import com.darkcom.backend.generate.tables.GroupQuota;
import com.darkcom.backend.generate.tables.records.GroupQuotaRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupQuotaDao extends DAOImpl<GroupQuotaRecord, com.darkcom.backend.generate.tables.pojos.GroupQuota, String> {

    /**
     * Create a new GroupQuotaDao without any configuration
     */
    public GroupQuotaDao() {
        super(GroupQuota.T_GROUP_QUOTA, com.darkcom.backend.generate.tables.pojos.GroupQuota.class);
    }

    /**
     * Create a new GroupQuotaDao with an attached configuration
     */
    public GroupQuotaDao(Configuration configuration) {
        super(GroupQuota.T_GROUP_QUOTA, com.darkcom.backend.generate.tables.pojos.GroupQuota.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.darkcom.backend.generate.tables.pojos.GroupQuota object) {
        return object.getGroupId();
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.GroupQuota> fetchByGroupId(String... values) {
        return fetch(GroupQuota.T_GROUP_QUOTA.GROUP_ID, values);
    }

    /**
     * Fetch a unique record that has <code>group_id = value</code>
     */
    public com.darkcom.backend.generate.tables.pojos.GroupQuota fetchOneByGroupId(String value) {
        return fetchOne(GroupQuota.T_GROUP_QUOTA.GROUP_ID, value);
    }

    /**
     * Fetch records that have <code>quota_balance IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.GroupQuota> fetchByQuotaBalance(Integer... values) {
        return fetch(GroupQuota.T_GROUP_QUOTA.QUOTA_BALANCE, values);
    }

    /**
     * Fetch records that have <code>quota_limit IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.GroupQuota> fetchByQuotaLimit(Integer... values) {
        return fetch(GroupQuota.T_GROUP_QUOTA.QUOTA_LIMIT, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.GroupQuota> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(GroupQuota.T_GROUP_QUOTA.CREATED_TIME, values);
    }
}
