/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.daos;


import com.darkcom.backend.generate.tables.QuotaDetail;
import com.darkcom.backend.generate.tables.records.QuotaDetailRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuotaDetailDao extends DAOImpl<QuotaDetailRecord, com.darkcom.backend.generate.tables.pojos.QuotaDetail, Integer> {

    /**
     * Create a new QuotaDetailDao without any configuration
     */
    public QuotaDetailDao() {
        super(QuotaDetail.T_QUOTA_DETAIL, com.darkcom.backend.generate.tables.pojos.QuotaDetail.class);
    }

    /**
     * Create a new QuotaDetailDao with an attached configuration
     */
    public QuotaDetailDao(Configuration configuration) {
        super(QuotaDetail.T_QUOTA_DETAIL, com.darkcom.backend.generate.tables.pojos.QuotaDetail.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.darkcom.backend.generate.tables.pojos.QuotaDetail object) {
        return object.getDetailId();
    }

    /**
     * Fetch records that have <code>detail_id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByDetailId(Integer... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.DETAIL_ID, values);
    }

    /**
     * Fetch a unique record that has <code>detail_id = value</code>
     */
    public com.darkcom.backend.generate.tables.pojos.QuotaDetail fetchOneByDetailId(Integer value) {
        return fetchOne(QuotaDetail.T_QUOTA_DETAIL.DETAIL_ID, value);
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByGroupId(String... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>quota_balance IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByQuotaBalance(Integer... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.QUOTA_BALANCE, values);
    }

    /**
     * Fetch records that have <code>quota_limit IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByQuotaLimit(Integer... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.QUOTA_LIMIT, values);
    }

    /**
     * Fetch records that have <code>personal_quota IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByPersonalQuota(Integer... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.PERSONAL_QUOTA, values);
    }

    /**
     * Fetch records that have <code>start_time IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByStartTime(LocalDateTime... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.START_TIME, values);
    }

    /**
     * Fetch records that have <code>end_time IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByEndTime(LocalDateTime... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.END_TIME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByStatus(Integer... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.STATUS, values);
    }

    /**
     * Fetch records that have <code>posi_id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByPosiId(Integer... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.POSI_ID, values);
    }

    /**
     * Fetch records that have <code>posi_name IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByPosiName(String... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.POSI_NAME, values);
    }

    /**
     * Fetch records that have <code>created_time IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.QuotaDetail> fetchByCreatedTime(LocalDateTime... values) {
        return fetch(QuotaDetail.T_QUOTA_DETAIL.CREATED_TIME, values);
    }
}
