/*
 * This file is generated by jOOQ.
 */
package com.darkcom.backend.generate.tables.daos;


import com.darkcom.backend.generate.tables.UserInfo;
import com.darkcom.backend.generate.tables.records.UserInfoRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 小程序用户信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfoDao extends DAOImpl<UserInfoRecord, com.darkcom.backend.generate.tables.pojos.UserInfo, Long> {

    /**
     * Create a new UserInfoDao without any configuration
     */
    public UserInfoDao() {
        super(UserInfo.T_USER_INFO, com.darkcom.backend.generate.tables.pojos.UserInfo.class);
    }

    /**
     * Create a new UserInfoDao with an attached configuration
     */
    public UserInfoDao(Configuration configuration) {
        super(UserInfo.T_USER_INFO, com.darkcom.backend.generate.tables.pojos.UserInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Long getId(com.darkcom.backend.generate.tables.pojos.UserInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchById(Long... values) {
        return fetch(UserInfo.T_USER_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.darkcom.backend.generate.tables.pojos.UserInfo fetchOneById(Long value) {
        return fetchOne(UserInfo.T_USER_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>union_id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByUnionId(String... values) {
        return fetch(UserInfo.T_USER_INFO.UNION_ID, values);
    }

    /**
     * Fetch records that have <code>open_id IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByOpenId(String... values) {
        return fetch(UserInfo.T_USER_INFO.OPEN_ID, values);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByPhone(String... values) {
        return fetch(UserInfo.T_USER_INFO.PHONE, values);
    }

    /**
     * Fetch records that have <code>nick_name IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByNickName(String... values) {
        return fetch(UserInfo.T_USER_INFO.NICK_NAME, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByGender(String... values) {
        return fetch(UserInfo.T_USER_INFO.GENDER, values);
    }

    /**
     * Fetch records that have <code>language IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByLanguage(String... values) {
        return fetch(UserInfo.T_USER_INFO.LANGUAGE, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByCity(String... values) {
        return fetch(UserInfo.T_USER_INFO.CITY, values);
    }

    /**
     * Fetch records that have <code>province IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByProvince(String... values) {
        return fetch(UserInfo.T_USER_INFO.PROVINCE, values);
    }

    /**
     * Fetch records that have <code>country IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByCountry(String... values) {
        return fetch(UserInfo.T_USER_INFO.COUNTRY, values);
    }

    /**
     * Fetch records that have <code>avatar_url IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByAvatarUrl(String... values) {
        return fetch(UserInfo.T_USER_INFO.AVATAR_URL, values);
    }

    /**
     * Fetch records that have <code>session_key IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchBySessionKey(String... values) {
        return fetch(UserInfo.T_USER_INFO.SESSION_KEY, values);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByCreatedBy(String... values) {
        return fetch(UserInfo.T_USER_INFO.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>create_date IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByCreateDate(LocalDateTime... values) {
        return fetch(UserInfo.T_USER_INFO.CREATE_DATE, values);
    }

    /**
     * Fetch records that have <code>updated_by IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByUpdatedBy(String... values) {
        return fetch(UserInfo.T_USER_INFO.UPDATED_BY, values);
    }

    /**
     * Fetch records that have <code>update_date IN (values)</code>
     */
    public List<com.darkcom.backend.generate.tables.pojos.UserInfo> fetchByUpdateDate(LocalDateTime... values) {
        return fetch(UserInfo.T_USER_INFO.UPDATE_DATE, values);
    }
}
